### ISSUE TITLE
recipesage_ingredient-instruction-classifier_1 container in restart loop stderr Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by DiversityBug** [julianpoy/RecipeSage-selfhost#10]
The recipesage_ingredient-instruction-classifier_1 container is caught in a loop constantly restarting.
The error logged is **Illegal instruction (core dumped)** - Stream stderr.
Please let me know if further information may be provided.

**Comment by julianpoy** [comment]
Hi DiversityBug,

Any additional info you can provide will be helpful. I've never seen the error that you're experiencing, but if I had to guess, I'd say it's likely due to tensorflow since that's just about the only dependency.

Here's the repo for the ingredient-instruction-classifier:
https://github.com/julianpoy/ingredient-instruction-classifier

The classifier is only used for the automatic recipe import feature, so the rest of the app should function just fine in the meantime.

**Comment by DiversityBug** [comment]
Hi Julian,
Thanks for your swift reply.
Maybe this is caused by the virtual environment (Synology NAS Disk Station Manager) I've been testing in. 
`Linux DSM7beta 4.4.180+ #41222 SMP Fri Dec 4 19:02:11 CST 2020 x86_64 GNU/Linux synology_kvmx64_virtualdsm`

I'm trying to install it straight on a PopOS machine. So far even the install of the proxy container went better. I'm stuck now when registering it tells me "Seems there is no connection". 

Apologies if I nip away on your time but I'm very new to Docker and the CLI for Linux.
Any chance you would compile this to a [Synology Community Package](https://synocommunity.com/) or is there a Synology Docker integration manual? ;-D

**Comment by julianpoy** [comment]
Noticed your post in the other thread. This is almost certainly due to that virtual environment. If you're not able to create a container from the base nginx image locally (that's the proxy), then it's not something to do with this repository.

> I'm stuck now when registering it tells me "Seems there is no connection".
Do you have any network logs and container logs to go along with this? This usually means that requests aren't getting routed to the API correctly, and/or that you haven't run migrations on the API.

> Any chance you would compile this to a Synology Community Package
I don't have any Synology hardware and have limited time on my hands at the moment. If you'd like to make a PR with the necessary configuration, I'd be happy to publish it to their community registry.

> is there a Synology Docker integration manual
I have no idea - Synology is proprietary and I've never used their stuff. I'm sure there's probably a way though!

**Comment by DiversityBug** [comment]
Thanks for looking into this.
I will need to expand my education on all of this and do some more testing.
I'll post here with the results, which will take some time.
Feel free to close this for now.

Thank you and stay healthy!

**Comment by absolution1** [comment]
Hi there.
Great piece of software.

Unfortunately, I think I'm seeing the exact same problem with the `recipesage_ingredient-instruction-classifier` container constantly restarting with the log showing: `Illegal instruction (core dumped)`

I am running ubuntu server, rather than dedicated NAS software.
I think the only niche thing I'm doing is hiding the forward facing part of recipe sage (which I guess is nginx) behind a reverse proxy, provided by caddy.
Is the reverse proxy causing the issue?  Anything I can do to help diagnose this?
