### ISSUE TITLE
recipesage_ingredient-instruction-classifier_1 container constantly restarting.  Log says 'Illegal instruction (core dumped)'

### ISSUE THREAD

**Issue by absolution1** [julianpoy/RecipeSage-selfhost#14]
Hi there.
Great piece of software.

Unfortunately, I think I'm seeing the exact same problem as: I have having the same issue as: https://github.com/julianpoy/RecipeSage-selfhost/issues/10
where the recipesage_ingredient-instruction-classifier container is constantly restarting with the log showing: Illegal instruction (core dumped)

I am running ubuntu server, rather than dedicated NAS software (unlike the setup reported by the other issue submitter).
I think the only niche thing I'm doing is hiding the forward facing part of recipe sage (which I guess is nginx) behind a reverse proxy, provided by caddy.
Is the reverse proxy causing the issue? Anything I can do to help diagnose this?

**Comment by julianpoy** [comment]
Hey there! It's been almost a month since this issue was opened so not sure if you found another path or are still dealing with this problem. I don't receive notifications for GitHub (probably should fix that).

If you wouldn't mind posting your logs that would be helpful. Unfortunately this is something to do with Tensorflow.JS rather than the project as a whole, so it makes it tricky to debug.

**Comment by julianpoy** [comment]
Hi @absolution1 I'll spend some time tomorrow trying to replicate the issue on my machines here and hopefully narrow down what's actually happening here.

**Comment by absolution1** [comment]
Is this on the host machine?  If so, `avx` is not in the list.

**Comment by julianpoy** [comment]
Yep, on the host machine.

Unfortunately AVX instruction support is required for Tensorflow from my reading.

AFAIK nothing that I can do about this, so sorry!
