### ISSUE TITLE
Cannot delete or edit recipes 4.1.0

### ISSUE THREAD

**Issue by theowoo** [julianpoy/RecipeSage-selfhost#77]
**Describe the issue**

- Cannot delete or edit recipes in v4.1.0.
  - Received error message: "An unexpected error occurred. Please check your server logs as well as the self hosting FAQ."
- Can add new recipes. (Same error occurred but the recipe appears upon reload.)

**Please do the following and check the boxes before filing**
- [x] I have attached my [docker_compose.yml](https://github.com/user-attachments/files/16195452/compose_sage_yaml.txt) to the issue
- [x] I have attached the [logs](https://github.com/user-attachments/files/16195441/recipesage_api.log) for my `api` container to the issue
- [ ] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

**Comment by julianpoy** [comment]
Hi there -- will need your Typesense container logs for this one, since it seems like there's a configuration issue with Typesense based on your API logs.

**Comment by theowoo** [comment]
Hi, thank you for looking into it. Here's the log:
[recipesage_typesense.log](https://github.com/user-attachments/files/16195963/recipesage_typesense.log)

**Comment by julianpoy** [comment]
At work so can't assist in debugging, but the logs for Typesense look good.

Given that the network configuration is modified in your docker-compose, and spinning up a fresh selfhost instance without modification works correctly, I believe the issue is related to the networking changes you've made and not the selfhost/recipesage repos. The error in the API container indicates it cannot reach the Typesense instance.

**Comment by theowoo** [comment]
Thank you for helping me troubleshoot. Indeed, everything worked again after restarting typesense. Keep up the good work!
